[workspace]
members = ["bindgen-utils", "generate", "ghc-rts-sys"]
resolver = "3"

[workspace.package]
version = "0.0.0"
edition = "2024"
rust-version = "1.85"

[workspace.metadata]
crane.name = "ghc-rts"

[workspace.dependencies]
# bindgen-0.71.1 is incompatible with edition 2024.
bindgen = { git = "https://github.com/rust-lang/rust-bindgen", rev = "a10bcfd0dd1e23c0139355deb567d83bd4b8a013" }
bindgen-utils = { path = "bindgen-utils" }
libc = "0.2.171"

[package]
name = "ghc-rts"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["staticlib"]

[features]
default = ["sys", "tracing"]
sys = []
tracing = ["dep:tracing"]

[dependencies]
ghc-rts-sys = { path = "ghc-rts-sys" }
libc.workspace = true
tracing = { version = "0.1.41", optional = true }

[dev-dependencies]
quickcheck = "1.0.3"
