[workspace]
members = ["build-utils", "generate", "ghc-rts-sys", "include", "rts"]
default-members = ["rts"]
resolver = "3"

[workspace.package]
version = "0.0.0"
edition = "2024"
rust-version = "1.85"

[workspace.metadata]
crane.name = "ghc-rts"

[workspace.dependencies]
# bindgen-0.71.1 is incompatible with edition 2024.
bindgen = { git = "https://github.com/rust-lang/rust-bindgen", rev = "97ab9152b5edb1fda1ced9bc1604f5e4dc9cfaa9" }
build-utils = { path = "build-utils" }
libc = "0.2.171"
